site_name: 「すーぱーおくてっと！」取扱説明書
theme: cinder
nav:
  - はじめに: index.md
  - ファームウェア更新:
    - ファームウェア更新: FW_UPDATE/fw.md
    - 波形生成プロセッサ: FW_UPDATE/tg.md
    - 周辺制御プロセッサ: FW_UPDATE/pp.md
  - MIDI仕様:
    - インプリメンテーション: MIDI_SPEC/impl.md
    - システムエクスクルーシブ: MIDI_SPEC/sysex.md
  - 免責・注意事項: CAUTIONS/cautions.md
  - ライセンス表示: license.md
  
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html
