site_name: すーぱーおくてっと！取扱説明書
theme: cinder
nav:
  - はじめに: index.md
  - 使い方ガイド:
    - 電源投入まで: GUIDE/tutorial_init.md
    - 本体の操作: GUIDE/tutorial_hard.md
    - PCで使う: GUIDE/tutorial_play.md
    - ファームウェア更新: fwupdate.md
  - 仕様:
    - MMXについて: SPEC/mmx.md
    - MIDIインプリメンテーション: SPEC/impl.md
    - システムエクスクルーシブ: SPEC/sysex.md
  - ダウンロード: download.md
  - ライセンス: license.md

markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - md_in_html

theme:
  name: cinder
  # Turn off Previous/Next navigation links in the navbar
  disable_nav_previous_next: true
  # Turn off Search in the navbar
  disable_nav_search: true
  # Turn off the site_name link in the navbar
  disable_nav_site_name: false
  # Turn off the footer entirely
  disable_footer: true
  # Turn off the default footer message, but display the page revision date if it's available
  disable_footer_except_revision: true
